name: 'Build and Attest Project'
description: 'Build mod project and upload an attestated zipfile'
inputs:
  modinfo:
    description: 'Modinfo JSON'
    required: true
# next steps:
#   - the release draft gets the artifact from the build, the metadata from the chained update and the commit hash from commit; all run together there
#   - figure out how to do the changelog
#   - after that, figure out how to automatically create the next SemVer version so that the workflow dispatch can run without any arguments
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Update Modinfo
      shell: bash
      run: |
        cat <<EOF | jq -c 'del(.["$schema"])' > modinfo.json
        ${{ inputs.modinfo }}
        EOF
    - name: Download Vintage Story
      shell: bash
      run: |
        cd $RUNNER_TEMP
        curl -fSL "https://cdn.vintagestory.at/gamefiles/stable/vs_client_linux-x64_1.22.0.tar.gz" -o vintagestory.tar.gz
        tar -xzf "vintagestory.tar.gz"
    - name: Build Project
      shell: bash
      run: dotnet publish -o dist -p:DirectoryBuildPropsPath=${{ github.action_path }}/Directory.Build.props -p:CI=true
    - name: (debug) List Files in Dist
      shell: bash
      run: ls dist
